name: 开始每日签到

on:
  workflow_dispatch:
  schedule:
    # UTC 1点30分(北京时间 9点30分)
    - cron: 30 1 * * *
  # 标星时触发工作流程
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run checkin
        run: |
          python3 glados.py
        env: 
          GLADOS_COOKIE: "koa:sess=eyJ1c2VySWQiOjExMjkyNywiX2V4cGlyZSI6MTcyMTI5MDA5MzM0OSwiX21heEFnZSI6MjU5MjAwMDAwMDB9; koa:sess.sig=OBlGR9b5ze1oh2xRERIFAM26hLg; __stripe_mid=515e8852-e874-404d-8d59-30c61d691cc1a5b772; _gid=GA1.2.280649475.1700660040; _ga=GA1.1.401530355.1695370054; __stripe_sid=0a813082-1f68-4a86-abaa-e8f0f3b57105063f88; _ga_CZFVKMNT9J=GS1.1.1700660040.4.1.1700660657.0.0.0"
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      - uses: gautamkrishnar/keepalive-workflow@master  
